# Generated by Django 5.0.6 on 2024-06-27 07:51

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistpage',
            name='hero_block',
            field=wagtail.fields.StreamField([('hero_block', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(help_text='Add you Heading', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add your Image', required=False))]))], blank=True, null=True),
        ),
    ]
