# Generated by Django 5.0.6 on 2024-06-27 10:48

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_assistpage_second_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistpage',
            name='hero_block',
            field=wagtail.fields.StreamField([('hero_block', wagtail.blocks.StructBlock([('banner_title', wagtail.blocks.CharBlock(help_text='Add you Heading', required=True)), ('banner_sub_title', wagtail.blocks.CharBlock(help_text='Add you Sub Heading', required=True)), ('banner_image', wagtail.images.blocks.ImageChooserBlock(help_text='Add your Image', required=False))]))], blank=True, null=True),
        ),
    ]
